language: java
jdk: openjdk8
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
install:
    - gpg --import $GPG_DIR/secret.gpg
    - cd Project/asynchelper
    - chmod a+x "$GPG_DIR/publish.sh"
    - "$GPG_DIR/publish.sh"
after_success:
    - mvn test jacoco:report coveralls:report
env:
  global:
  - GPG_DIR="`pwd`/deploy"
