language: java
jdk: openjdk8
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
install:
    - gpg --import $GPG_DIR/secret.gpg
    - cd "$PROJ_DIR/Project/asynchelper"
    - mvn install
after_success:
    - cd "$PROJ_DIR/Project/asynchelper"
    - chmod a+x "$GPG_DIR/publish.sh"
    - "$GPG_DIR/publish.sh"
env:
  global:
  - PROJ_DIR=`pwd`
  - GPG_DIR="$PROJ_DIR/deploy"
