language: java
jdk: openjdk8
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
install:
    - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
    - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
    - gpg --import $GPG_DIR/secring.gpg
    - cd Project/asynchelper
    - chmod a+x "$GPG_DIR/publish.sh"
    - "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
